Upgrade bin scripts

diff --git a/bin/pomodoro b/bin/pomodoro
--- a/bin/pomodoro
+++ b/bin/pomodoro
@@ -1,30 +1,31 @@
 #!/usr/bin/env bash
 
-#######################################################################
-# pomodoro.sh
-#
-# Pomodoro technique counter for study sessions.
-# > https://en.wikipedia.org/wiki/Pomodoro_Technique
-#
-# Copyright (C) 2017-2019 Brainfuck
-#
-#
-# GNU GENERAL PUBLIC LICENSE
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-#
-#######################################################################
+################################################################################
+#                                                                              #
+# pomodoro.sh                                                                  #
+#                                                                              #
+# Pomodoro technique counter for study sessions.                               #
+# > https://en.wikipedia.org/wiki/Pomodoro_Technique                           #
+#                                                                              #
+# Copyright (C) 2017-2022 brainf+ck                                            #
+#                                                                              #
+#                                                                              #
+# GNU GENERAL PUBLIC LICENSE                                                   #
+#                                                                              #
+# This program is free software: you can redistribute it and/or modify         #
+# it under the terms of the GNU General Public License as published by         #
+# the Free Software Foundation, either version 3 of the License, or            #
+# (at your option) any later version.                                          #
+#                                                                              #
+# This program is distributed in the hope that it will be useful,              #
+# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
+# GNU General Public License for more details.                                 #
+#                                                                              #
+# You should have received a copy of the GNU General Public License            #
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.        #
+#                                                                              #
+################################################################################
 
 
 # set command: https://ss64.com/bash/set.html
@@ -33,8 +34,8 @@ set -eo pipefail
 
 # Program information
 readonly program_name="pomodoro"
-readonly version="0.3.1"
-readonly author="Brainfuck"
+readonly version="0.4.2"
+readonly author="brainf+ck"
 
 # Arguments, arguments num
 readonly args="$*"
@@ -61,8 +62,8 @@ readonly longpause_time=900
 # done_list = file to write the pomodoros completed
 # image = image shown with notify-d
 readonly done_list="/tmp/pomodoros.txt"
-readonly image="$HOME/.local/share/pomodoro/fs.png"
-readonly notice_sound="$HOME/.local/share/pomodoro/alarm.wav"
+readonly image="${HOME}/.local/share/pomodoro/fs.png"
+readonly notice_sound="${HOME}/.local/share/pomodoro/alarm.wav"
 
 
 # Exit from program if user type Ctrl+c
@@ -90,14 +91,11 @@ time_format() {
 
 # Show program version
 show_version() {
-    printf "%s\\n" "$program_name $version"
-    printf "%s\\n" "Copyright (C) 2017-2019 Brainfuck"
-    printf "%s\\n" \
-           "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
-    printf "%s\\n" \
-           "This is free software: you are free to change and redistribute it."
-    printf "%s\\n" \
-           "There is NO WARRANTY, to the extent permitted by law."
+    printf "%s\\n" "${program_name} ${version}"
+    printf "%s\\n" "Copyright (C) 2017-2022 brainf+ck"
+    printf "%s\\n" "License GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
+    printf "%s\\n" "This is free software: you are free to change and redistribute it."
+    printf "%s\\n" "There is NO WARRANTY, to the extent permitted by law."
     exit 0
 }
 
@@ -109,24 +107,24 @@ banner() {
  ___ ___ _____ ___ _| |___ ___ ___
 | . | . |     | . | . | . |  _| . |
 |  _|___|_|_|_|___|___|___|_| |___|
-|_|                                v$version
+|_|                                v${version}
 
 Pomodoro technique counter for study sessions
-Author: $author
+Author: ${author}
 ${endc}\\n\\n"
 }
 
 
 # Write pomodoros completed to done list
 add_to_list() {
-    printf "%s\\n" "[*] pomodoro++ - $(time_format 'my_date')" >>"$done_list"
+    printf "%s\\n" "[*] pomodoro++ - $(time_format 'my_date')" >> "${done_list}"
 }
 
 
 # Delete pomodoros list
 delete_list() {
-    if [ -f "$done_list" ]; then
-        rm "$done_list"
+    if [[ -f "${done_list}" ]]; then
+        rm "${done_list}"
         printf "${green}%s${endc}\\n" "[i] pomodoros list deleted"
         exit 0
     else
@@ -138,11 +136,11 @@ delete_list() {
 
 # Show pomodoros completed
 show_completed() {
-    if [[ ! -f "$done_list" ]]; then
+    if [[ ! -f "${done_list}" ]]; then
         printf "${red}%s${endc}\\n" "[i] No pomodoros have been completed"
         exit 0
     else
-        less -FX "$done_list"
+        less -FX "${done_list}"
     fi
 }
 
@@ -158,24 +156,24 @@ display_info() {
     # notify-send -t, --expire-time=TIME, -i, --icon=ICON [MSG]
     case "$1" in
         start)
-            notify-send -t 10000 -i "$image" "$msg_1"
+            notify-send -t 10000 -i "${image}" "${msg_1}"
             printf "${bgreen}%s ${white}%s ${bblue}%s${endc}\\n" \
                 "==>" "$(time_format 'my_time'):" "$msg_1"
         ;;
         pause)
-            notify-send -t 10000 -i "$image" "$msg_2"
+            notify-send -t 10000 -i "${image}" "${msg_2}"
             printf "${bred}%s ${white}%s ${bblue}%s${endc}\\n" \
-                   "==>" "$(time_format 'my_time'):" "$msg_2"
+                "==>" "$(time_format 'my_time'):" "$msg_2"
         ;;
         long_pause)
-            notify-send -t 10000 -i "$image" "$msg_3"
+            notify-send -t 10000 -i "${image}" "${msg_3}"
             printf "${bred}%s ${white}%s ${bblue}%s${endc}\\n" \
-                   "==>" "$(time_format 'my_time'):" "$msg_3"
+                "==>" "$(time_format 'my_time'):" "$msg_3"
         ;;
         end_session)
-            notify-send -t 10000 -i "$image" "$msg_4"
+            notify-send -t 10000 -i "${image}" "${msg_4}"
             printf "${bgreen}%s ${white}%s ${bblue}%s${endc}\\n" \
-                   "==>" "$(time_format 'my_time'):" "$msg_4"
+                "==>" "$(time_format 'my_time'):" "${msg_4}"
 
             printf "\\n${white}%s${endc}\\n\\n" "A day without learning is a day wasted"
         ;;
@@ -188,8 +186,8 @@ display_info() {
 # try 2 = `paplay` (Pulseaudio)
 # do nothing if the sound can not be played.
 play_sound() {
-    if ! aplay --quiet "$notice_sound" 2>/dev/null; then
-        paplay "$notice_sound" 2>/dev/null;
+    if ! aplay --quiet "${notice_sound}" 2>/dev/null; then
+        paplay "${notice_sound}" 2>/dev/null;
     else
         :
     fi
@@ -197,7 +195,7 @@ play_sound() {
 
 
 # Check the user input
-check_input(){
+check_input() {
     # for option `-p, --pomodoros`,
     # the only valid argument is an integer of 1 to 100.
     if [[ ! "${pomodoros}" =~ ^([1-9]|1[0-9]|2[0-9]|100)$ ]]; then
@@ -214,7 +212,7 @@ start_counter() {
 
 	# begin pomodoros cycle
     local count_cycle=0
-	for ((c = 1; c <= "$pomodoros"; c++)); do
+	for ((c = 1; c <= "${pomodoros}"; c++)); do
         count_cycle="$((count_cycle + 1))"
 
         # start 25 min pomodoro session
@@ -223,28 +221,28 @@ start_counter() {
         play_sound
 
         # sleep for N minutes (`session_time`)
-        sleep "$session_time"
+        sleep "${session_time}"
 
         # add pomodoro to list at the end of session
         add_to_list
 
         # make long pause (15 min) after 4 pomodoros
-        if [[ "$count_cycle" = 4 ]]; then
+        if [[ "${count_cycle}" = 4 ]]; then
             display_info "long_pause"
             play_sound
             count_cycle=0
-            sleep "$longpause_time"
+            sleep "${longpause_time}"
         else
         # short pause (5 min) after each pomodoro
             display_info "pause"
             play_sound
-            sleep "$pause_time"
+            sleep "${pause_time}"
         fi
 	done
 
     # end session and show pomodoros done
     display_info "end_session"
-    less -FX "$done_list"
+    less -FX "${done_list}"
 
 	exit 0
 }
@@ -253,12 +251,14 @@ start_counter() {
 # Show help menù
 usage() {
 cat << EOF
-$program_name $version
+${program_name} ${version}
 Pomodoro technique counter for study sessions.
+Author: ${author}
 
-Usage: $program_name [option]
+Usage: ${program_name} [option]
 
 Options:
+
 -h, --help              Show this help menù
 -p, --pomodoros [n]     Number of pomodoros
 -l, --list              Show completed pomodoros
@@ -271,10 +271,10 @@ EOF
 # Main function: parse command line options.
 # Thanks to dgoguerra for this 'getopt handmade' implementation
 # see: https://gist.github.com/dgoguerra/9206418
-main(){
-    if [ "$#" -eq 0 ]; then
-        printf "%s\\n" "$program_name: Argument required"
-        printf "%s\\n" "Try '$program_name --help' for more information."
+main() {
+    if [[ "$#" -eq 0 ]]; then
+        printf "%s\\n" "${program_name}: Argument required"
+        printf "%s\\n" "Try '${program_name} --help' for more information."
         exit 1
     fi
 
@@ -305,8 +305,10 @@ main(){
                 exit 1
                 ;;
         esac
-        shift
+        exit 0
     done
 }
 
-main "$@"
+# Call main
+main "${@}"
+
diff --git a/bin/rbackup b/bin/rbackup
--- a/bin/rbackup
+++ b/bin/rbackup
@@ -6,7 +6,7 @@
 #
 # Shell script for make encrypted backups with rsync and GnuPG
 #
-# Copyright (C) 2018-2021 Brainfuck
+# Copyright (C) 2018-2021 Brainf+ck
 #
 #
 # GNU GENERAL PUBLIC LICENSE
@@ -33,12 +33,8 @@
 
 # Program information
 readonly prog_name="rbackup"
-readonly version="0.6.1"
-readonly signature="Copyright (C) 2021 Brainfuck"
-
-# Initialize arguments
-readonly args="$*"
-readonly argnum="$#"
+readonly version="0.7.0"
+readonly signature="Copyright (C) 2021 Brainf+ck"
 
 # Date format used for entries in the log file: `YYYY/mm/dd H:M:S`
 readonly current_date="$(date +'%Y/%m/%d %T')"
@@ -83,7 +79,7 @@ readonly log_file="${dest_dir}/rbackup-$(date +'%Y-%m-%d').log"
 
 ## Error except: write a message in the log file and exit with (1)
 die() {
-    printf "%s\\n" "${current_date} $@" >>"${log_file}"
+    printf "%s\\n" "${current_date} $*" >>"${log_file}"
     exit 1
 }
 
@@ -155,24 +151,26 @@ start_backup() {
     # date format: `YYYY-mm-dd`
     local filename="${label}-$(date +'%Y-%m-%d')"
 
-    # TODO: Insert rsync options in the config file
-    #
-    # exec rsync command:
-    #
-    # -ahv --delete --log-file=<file> --exclude-file=<file>
+    # run rsync main command:
     #
     # --archive, -a            archive mode; equals -rlptgoD (no -H,-A,-X)
     # --human-readable, -h     output numbers in a human-readable format
     # --one-file-system, -x    don't cross filesystem boundaries
-    # --verbose, -v            increase verbosity
     # --delete                 delete extraneous files from dest dirs
+    # --info=progress2         show total transfer progress
     # --log-file=FILE          log what we're doing to the specified FILE
     # --exclude-from=FILE      read exclude patterns from FILE
     #
     # rsync --help | man rsync for more information
-    if ! rsync -ahxv --delete --log-file="${log_file}" --exclude-from="${exclude_file}" \
-               "${source_dir}" "${dest_dir}/${filename}"; then
-        die " [Error]: rsync command failed."
+    if ! rsync \
+        -ahx \
+        --delete \
+        --info=progress2 \
+        --log-file="${log_file}" \
+        --exclude-from="${exclude_file}" \
+        "${source_dir}" "${dest_dir}/${filename}"; then
+
+        die "[Error]: rsync command failed."
     fi
 
     # create tar/gzip archive
@@ -250,4 +248,5 @@ main() {
     done
 }
 
-main "$@"
+# Call main
+main "${@}"
